### ISSUE TITLE
problem cookies - credentials

### ISSUE THREAD

**Issue by fermani10** [Borodutch/VideoDownloadBot#4]
Hello, I have a problem I place cookies or credentials in credentials.json but in the same way it does not download me from instagram and facebook. How could I do it to solve? thank you in advance, or could you give me an example of a cookie and where does it go? Thank you.

**Comment by backmeupplz** [comment]
I no longer use `credentials.json`. Please, see the readme on where to put the credentials and/or cookies :) thank you!
